# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greet.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'greet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgreet.proto\x12\x05greet\"\'\n\x05Hello\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08greeting\x18\x02 \x01(\t\"\x19\n\x05Reply\x12\x10\n\x08greeting\x18\x01 \x01(\t\"<\n\tMoreHello\x12\x10\n\x08greeting\x18\x01 \x01(\t\x12\x1d\n\x07request\x18\x02 \x03(\x0b\x32\x0c.greet.Hello2\xc3\x01\n\x07Greeter\x12&\n\x08SayHello\x12\x0c.greet.Hello\x1a\x0c.greet.Reply\x12/\n\x0b\x43lientHello\x12\x0c.greet.Hello\x1a\x10.greet.MoreHello(\x01\x12+\n\x0bServerHello\x12\x0c.greet.Hello\x1a\x0c.greet.Reply0\x01\x12\x32\n\x10InteractiveHello\x12\x0c.greet.Hello\x1a\x0c.greet.Reply(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLO']._serialized_start=22
  _globals['_HELLO']._serialized_end=61
  _globals['_REPLY']._serialized_start=63
  _globals['_REPLY']._serialized_end=88
  _globals['_MOREHELLO']._serialized_start=90
  _globals['_MOREHELLO']._serialized_end=150
  _globals['_GREETER']._serialized_start=153
  _globals['_GREETER']._serialized_end=348
# @@protoc_insertion_point(module_scope)
