events{}

http{

    include mime.types;

    gzip on;

    server{

        listen 80;
        server_name localhost;

        root D:/Nginx/demo-site/demo;

        #index index.html;

        # try_files /dog.png /greets @nothing;

        location /greet {
            return 200 'Greetings from nginx';
        }

        location @nothing {
            return 404 'Nothing found here !!';
        }

        # location /inspect {

        #     return 200 '$host\n$args';
        # }


        # location /logo {
        #      return 307 thumb.png;
        # }

        location /logo {
            add_header my_header "Hello world";
            return 200 'Logo endpoint reached';
        }

    }
}