# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import greet_pb2 as greet__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in greet_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GreeterStub:
    """Define services
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/greet.Greeter/SayHello',
                request_serializer=greet__pb2.Hello.SerializeToString,
                response_deserializer=greet__pb2.Reply.FromString,
                _registered_method=True)
        self.ClientHello = channel.stream_unary(
                '/greet.Greeter/ClientHello',
                request_serializer=greet__pb2.Hello.SerializeToString,
                response_deserializer=greet__pb2.MoreHello.FromString,
                _registered_method=True)
        self.ServerHello = channel.unary_stream(
                '/greet.Greeter/ServerHello',
                request_serializer=greet__pb2.Hello.SerializeToString,
                response_deserializer=greet__pb2.Reply.FromString,
                _registered_method=True)
        self.InteractiveHello = channel.stream_stream(
                '/greet.Greeter/InteractiveHello',
                request_serializer=greet__pb2.Hello.SerializeToString,
                response_deserializer=greet__pb2.Reply.FromString,
                _registered_method=True)


class GreeterServicer:
    """Define services
    """

    def SayHello(self, request, context):
        """Unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientHello(self, request_iterator, context):
        """Client Streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerHello(self, request, context):
        """Server Streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InteractiveHello(self, request_iterator, context):
        """Bi-Directional Streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=greet__pb2.Hello.FromString,
                    response_serializer=greet__pb2.Reply.SerializeToString,
            ),
            'ClientHello': grpc.stream_unary_rpc_method_handler(
                    servicer.ClientHello,
                    request_deserializer=greet__pb2.Hello.FromString,
                    response_serializer=greet__pb2.MoreHello.SerializeToString,
            ),
            'ServerHello': grpc.unary_stream_rpc_method_handler(
                    servicer.ServerHello,
                    request_deserializer=greet__pb2.Hello.FromString,
                    response_serializer=greet__pb2.Reply.SerializeToString,
            ),
            'InteractiveHello': grpc.stream_stream_rpc_method_handler(
                    servicer.InteractiveHello,
                    request_deserializer=greet__pb2.Hello.FromString,
                    response_serializer=greet__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'greet.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('greet.Greeter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Greeter:
    """Define services
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/greet.Greeter/SayHello',
            greet__pb2.Hello.SerializeToString,
            greet__pb2.Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClientHello(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/greet.Greeter/ClientHello',
            greet__pb2.Hello.SerializeToString,
            greet__pb2.MoreHello.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/greet.Greeter/ServerHello',
            greet__pb2.Hello.SerializeToString,
            greet__pb2.Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InteractiveHello(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/greet.Greeter/InteractiveHello',
            greet__pb2.Hello.SerializeToString,
            greet__pb2.Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
