# Run Nginx as the "nginx" user
user nginx;
# Automatically determine the number of worker processes based on available CPU cores
worker_processes auto;

events {
    # Maximum number of simultaneous connections per worker process
    worker_connections 1024;
}

http {
    # Include mapping of file extensions to MIME types
    include /etc/nginx/mime.types;
    # Default MIME type for unknown files
    default_type application/octet-stream;
    
    # Enable highly efficient file transfer
    sendfile on;
    # Maximum time to keep an idle connection open
    keepalive_timeout 65;
    
    # Include all configuration files from the conf.d directory (like default.conf)
    include /etc/nginx/conf.d/*.conf;
}
